# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\home_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_HomeWindow(object):
    def setupUi(self, HomeWindow):
        HomeWindow.setObjectName("HomeWindow")
        HomeWindow.resize(1319, 797)
        HomeWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(HomeWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(230, 0, 1200, 800))
        self.widget.setStyleSheet("* {\n"
"    background-color: #ffffff;\n"
"    font-style: \"Segoe UI\";\n"
"     color: #0B090A;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #fbba72;\n"
"    border-radius: 20px;\n"
"    font-size: 22px;\n"
"    font-weight: regular;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #399918;\n"
"    border: 2px solid #333;\n"
"    color: #EEEEEE;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #6703c5;\n"
"    color: #EEEEEE;\n"
"}\n"
"")
        self.widget.setObjectName("widget")
        self.btn_dashboard = QtWidgets.QPushButton(self.widget)
        self.btn_dashboard.setGeometry(QtCore.QRect(130, 260, 221, 131))
        self.btn_dashboard.setMinimumSize(QtCore.QSize(221, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        self.btn_dashboard.setFont(font)
        self.btn_dashboard.setStyleSheet("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/icon/relatorio.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_dashboard.setIcon(icon)
        self.btn_dashboard.setIconSize(QtCore.QSize(64, 64))
        self.btn_dashboard.setObjectName("btn_dashboard")
        self.btn_engenharia = QtWidgets.QPushButton(self.widget)
        self.btn_engenharia.setGeometry(QtCore.QRect(440, 260, 221, 131))
        self.btn_engenharia.setMinimumSize(QtCore.QSize(221, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        self.btn_engenharia.setFont(font)
        self.btn_engenharia.setStyleSheet("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon/icon/engenharia.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_engenharia.setIcon(icon1)
        self.btn_engenharia.setIconSize(QtCore.QSize(64, 64))
        self.btn_engenharia.setObjectName("btn_engenharia")
        self.btn_pcp = QtWidgets.QPushButton(self.widget)
        self.btn_pcp.setGeometry(QtCore.QRect(750, 260, 221, 131))
        self.btn_pcp.setMinimumSize(QtCore.QSize(221, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        self.btn_pcp.setFont(font)
        self.btn_pcp.setStyleSheet("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icon/icon/producao.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_pcp.setIcon(icon2)
        self.btn_pcp.setIconSize(QtCore.QSize(64, 64))
        self.btn_pcp.setObjectName("btn_pcp")
        self.btn_compras = QtWidgets.QPushButton(self.widget)
        self.btn_compras.setGeometry(QtCore.QRect(130, 470, 221, 131))
        self.btn_compras.setMinimumSize(QtCore.QSize(221, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        self.btn_compras.setFont(font)
        self.btn_compras.setStyleSheet("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icon/icon/carrinho-carrinho.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_compras.setIcon(icon3)
        self.btn_compras.setIconSize(QtCore.QSize(64, 64))
        self.btn_compras.setObjectName("btn_compras")
        self.btn_comercial = QtWidgets.QPushButton(self.widget)
        self.btn_comercial.setGeometry(QtCore.QRect(440, 470, 221, 131))
        self.btn_comercial.setMinimumSize(QtCore.QSize(221, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        self.btn_comercial.setFont(font)
        self.btn_comercial.setStyleSheet("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icon/icon/acordo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_comercial.setIcon(icon4)
        self.btn_comercial.setIconSize(QtCore.QSize(64, 64))
        self.btn_comercial.setObjectName("btn_comercial")
        self.btn_qps = QtWidgets.QPushButton(self.widget)
        self.btn_qps.setGeometry(QtCore.QRect(750, 470, 221, 131))
        self.btn_qps.setMinimumSize(QtCore.QSize(221, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        self.btn_qps.setFont(font)
        self.btn_qps.setStyleSheet("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icon/icon/pedir-comida.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_qps.setIcon(icon5)
        self.btn_qps.setIconSize(QtCore.QSize(64, 64))
        self.btn_qps.setCheckable(False)
        self.btn_qps.setObjectName("btn_qps")
        self.welcome_label = QtWidgets.QLabel(self.widget)
        self.welcome_label.setGeometry(QtCore.QRect(30, 70, 441, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.welcome_label.setFont(font)
        self.welcome_label.setStyleSheet("QLabel {\n"
"    background-color: transparent;\n"
"    color: #a4161a;\n"
"    font-size: 28px;\n"
"    font-weight: bold;\n"
"    font-style: \"Segoe UI\";\n"
"}")
        self.welcome_label.setObjectName("welcome_label")
        self.user_label = QtWidgets.QLabel(self.widget)
        self.user_label.setGeometry(QtCore.QRect(30, 10, 441, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.user_label.setFont(font)
        self.user_label.setStyleSheet("QLabel {\n"
"    background-color: transparent;\n"
"    color: #a4161a;\n"
"    font-size: 28px;\n"
"    font-weight: bold;\n"
"    font-style: \"Segoe UI\";\n"
"}")
        self.user_label.setObjectName("user_label")
        self.logo_enaplic_50 = QtWidgets.QLabel(self.widget)
        self.logo_enaplic_50.setGeometry(QtCore.QRect(950, 700, 121, 101))
        self.logo_enaplic_50.setText("")
        self.logo_enaplic_50.setPixmap(QtGui.QPixmap(":/image/image/logo_enaplic_50_anos.png"))
        self.logo_enaplic_50.setScaledContents(True)
        self.logo_enaplic_50.setObjectName("logo_enaplic_50")
        self.btn_close = QtWidgets.QPushButton(self.widget)
        self.btn_close.setGeometry(QtCore.QRect(1020, 10, 51, 51))
        self.btn_close.setMinimumSize(QtCore.QSize(0, 41))
        self.btn_close.setStyleSheet("* {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"}")
        self.btn_close.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icon/icon/excluir (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_close.setIcon(icon6)
        self.btn_close.setIconSize(QtCore.QSize(32, 32))
        self.btn_close.setObjectName("btn_close")
        self.sidebar_enaplic = QtWidgets.QWidget(self.centralwidget)
        self.sidebar_enaplic.setGeometry(QtCore.QRect(-10, 0, 241, 801))
        self.sidebar_enaplic.setStyleSheet("* {\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(186, 24, 27, 255), stop:1 rgba(102, 7, 8, 255));\n"
"}")
        self.sidebar_enaplic.setObjectName("sidebar_enaplic")
        self.logo_enaplic = QtWidgets.QLabel(self.sidebar_enaplic)
        self.logo_enaplic.setGeometry(QtCore.QRect(90, 40, 81, 81))
        self.logo_enaplic.setText("")
        self.logo_enaplic.setPixmap(QtGui.QPixmap(":/image/image/LOGO.jpeg"))
        self.logo_enaplic.setScaledContents(True)
        self.logo_enaplic.setObjectName("logo_enaplic")
        HomeWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(HomeWindow)
        QtCore.QMetaObject.connectSlotsByName(HomeWindow)

    def retranslateUi(self, HomeWindow):
        _translate = QtCore.QCoreApplication.translate
        HomeWindow.setWindowTitle(_translate("HomeWindow", "MainWindow"))
        self.btn_dashboard.setText(_translate("HomeWindow", "Dashboard"))
        self.btn_engenharia.setText(_translate("HomeWindow", "Engenharia"))
        self.btn_pcp.setText(_translate("HomeWindow", " PCP"))
        self.btn_compras.setText(_translate("HomeWindow", "Compras"))
        self.btn_comercial.setText(_translate("HomeWindow", "Comercial"))
        self.btn_qps.setText(_translate("HomeWindow", "Gestão QPS"))
        self.welcome_label.setText(_translate("HomeWindow", "Seja bem-vindo(a) ao Eureka!"))
        self.user_label.setText(_translate("HomeWindow", "Olá {user}"))
import resource_rc
