
SELECT 
	*
FROM 
	PROTHEUS12_R27.dbo.SC2010
WHERE
	C2_ZZNUMQP LIKE '%6963'
	AND D_E_L_E_T_ <> '*'
ORDER BY R_E_C_N_O_ DESC;


-- TOTAL DE OPs (ABERTAS E FECHADAS)
SELECT 
	COUNT(*) AS "TOTAL OPs"
FROM 
	SC2010
WHERE
	C2_ZZNUMQP LIKE '%6963'
	AND D_E_L_E_T_ <> '*';

	
-- TOTAL DE OPs (ABERTAS)
SELECT 
	COUNT(*) AS "OP ABERTA"
FROM 
	SC2010
WHERE
	C2_ZZNUMQP LIKE '%6963'
	AND C2_DATRF = '       '
	AND D_E_L_E_T_ <> '*';

	
-- TOTAL DE OPs (FECHADAS)
SELECT 
	COUNT(*) AS "OP FECHADA"
FROM 
	SC2010
WHERE
	C2_ZZNUMQP LIKE '%6963'
	AND C2_DATRF <> '       '
	AND D_E_L_E_T_ <> '*';

SELECT 
	C1_FILIAL, C1_NUM, C1_ITEM, C1_PRODUTO, C1_UM, C1_DESCRI, C1_QUANT, C1_PRECO, C1_TOTAL, C1_SEGUM, C1_QTSEGUM, C1_DATPRF, C1_OBS, C1_OP, C1_LOCAL, C1_CC, C1_CONTA, C1_ITEMCTA, C1_EMISSAO, C1_COTACAO, C1_FORNECE, C1_LOJA, C1_PEDIDO, C1_ITEMPED, C1_SOLICIT, C1_IDENT, C1_QUJE, C1_TX, C1_OK, C1_OS, C1_IMPORT, C1_UNIDREQ, C1_CODCOMP, C1_CLASS, C1_FABR, C1_FABRLOJ, C1_NUM_SI, C1_TPOP, C1_QUJE2, C1_GRUPCOM, C1_USER, C1_ORIGEM, C1_CLVL, C1_PROJETO, C1_FILENT, C1_SEQMRP, C1_VUNIT, C1_CONDPAG, C1_CODORCA, C1_RESIDUO, C1_QTDORIG, C1_TIPOEMP, C1_ESPEMP, C1_APROV, C1_TIPO, C1_MOEDA, C1_GERACTR, C1_LOJFABR, C1_NOMAPRO, C1_SIGLA, C1_FABRICA, C1_FLAGGCT, C1_QTDREEM, C1_PROGRAM, C1_ITEMGRD, C1_GRADE, C1_TPSC, C1_MODAL, C1_TPMOD, C1_CODED, C1_NUMPR, C1_ORCAM, C1_ESTOQUE, C1_REVISAO, C1_RATEIO, C1_ACCPROC, C1_ACCNUM, C1_ACCITEM, C1_IDAPS, C1_COMPRAC, C1_FISCORI, C1_ITSCORI, C1_SCORI, C1_USRCODE, C1_PRDREF, C1_PEDRES, C1_TIPCOM, C1_NRBPIMS, D_E_L_E_T_, R_E_C_N_O_, R_E_C_D_E_L_, C1_ZZNUMQP, C1_USERLGI, C1_USERLGA, C1_GRPRD, C1_XDTFIM, C1_XDTINI, C1_XHRFIM, C1_XHRINI, C1_XCLASSI, C1_XCONTFI, C1_PREFIX, C1_XSTGCT, C1_XCONTPR, C1_XGRPAPR, C1_XNUMCT, C1_XNUMREV, C1_XSOL, C1_XCTADT, C1_XTIPOSC, C1_XCONTPL, C1_XCONTIT, C1_DINICOM
FROM 
	PROTHEUS12_R27.dbo.SC1010
WHERE
	C1_ZZNUMQP LIKE '%6963'
	AND C1_PEDIDO = '      '
	--AND C1_PEDIDO = '010457'
ORDER BY R_E_C_N_O_ DESC;


-- TOTAL DE SCs (ABERTAS E FECHADAS)'
SELECT 
	COUNT(*) AS "SC ABERTA E FECHADA"
FROM 
	PROTHEUS12_R27.dbo.SC1010
WHERE
	C1_ZZNUMQP LIKE '%6963'
	AND D_E_L_E_T_ <> '*';
	

-- TOTAL DE SCs (ABERTAS)
SELECT 
	COUNT(*) AS "SC ABERTA"
FROM 
	PROTHEUS12_R27.dbo.SC1010
WHERE
	C1_ZZNUMQP LIKE '%6963'
	AND C1_PEDIDO = '      '
	AND D_E_L_E_T_ <> '*';
	

-- TOTAL DE SCs (FECHADAS)
SELECT 
	COUNT(*) AS "SC FECHADA"
FROM 
	PROTHEUS12_R27.dbo.SC1010
WHERE
	C1_ZZNUMQP LIKE '%6963'
	AND C1_PEDIDO <> '      '
	AND D_E_L_E_T_ <> '*';

    SELECT 
	C7_FILIAL, C7_TIPO, C7_ITEM, C7_PRODUTO, C7_UM, C7_SEGUM, C7_QUANT, C7_CODTAB, C7_PRECO, C7_TOTAL, C7_QTSEGUM, C7_IPI, C7_ITEMSC, C7_NUMSC, C7_DINICQ, C7_DINICOM, C7_DINITRA, C7_DATPRF, C7_LOCAL, C7_OBSM, C7_OBS, C7_FORNECE, C7_CC, C7_CONTA, C7_ITEMCTA, C7_LOJA, C7_COND, C7_CONTATO, C7_FILENT, C7_DESC1, C7_DESC2, C7_DESC3, C7_EMISSAO, C7_NUM, C7_QUJE, C7_REAJUST, C7_FRETE, C7_EMITIDO, C7_DESCRI, C7_TPFRETE, C7_QTDREEM, C7_CODLIB, C7_RESIDUO, C7_NUMCOT, C7_MSG, C7_TX, C7_CONTROL, C7_IPIBRUT, C7_ENCER, C7_OP, C7_VLDESC, C7_SEQUEN, C7_NUMIMP, C7_ORIGEM, C7_QTDACLA, C7_VALEMB, C7_FLUXO, C7_TPOP, C7_APROV, C7_CONAPRO, C7_GRUPCOM, C7_USER, C7_STATME, C7_RESREM, C7_OK, C7_QTDSOL, C7_VALIPI, C7_VALICM, C7_TES, C7_DESC, C7_PICM, C7_BASEICM, C7_BASEIPI, C7_SEGURO, C7_DESPESA, C7_VALFRE, C7_MOEDA, C7_TXMOEDA, C7_PENDEN, C7_CLVL, C7_BASEIR, C7_ALIQIR, C7_VALIR, C7_ICMCOMP, C7_ICMSRET, C7_BASIMP5, C7_BASIMP6, C7_VALSOL, C7_ESTOQUE, C7_SOLICIT, C7_VALIMP5, C7_VALIMP6, C7_SEQMRP, C7_CODORCA, C7_DTLANC, C7_CODCRED, C7_TIPOEMP, C7_ESPEMP, C7_CONTRA, C7_CONTREV, C7_PLANILH, C7_MEDICAO, C7_ITEMED, C7_FREPPCC, C7_POLREPR, C7_DT_IMP, C7_PERREPR, C7_AGENTE, C7_GRADE, C7_ITEMGRD, C7_FORWARD, C7_TIPO_EM, C7_ORIGIMP, C7_DEST, C7_COMPRA, C7_PESO_B, C7_INCOTER, C7_IMPORT, C7_CONSIG, C7_CONF_PE, C7_DESP, C7_EXPORTA, C7_LOJAEXP, C7_CONTAIN, C7_MT3, C7_CONTA20, C7_CONTA40, C7_CON40HC, C7_ARMAZEM, C7_FABRICA, C7_LOJFABR, C7_DT_EMB, C7_TEC, C7_EX_NCM, C7_EX_NBM, C7_BASESOL, C7_DIACTB, C7_NODIA, C7_PO_EIC, C7_CODED, C7_NUMPR, C7_FILEDT, C7_GCPIT, C7_GCPLT, C7_TIPCOM, C7_NUMSA, C7_ACCNUM, C7_ACCITEM, C7_REVISAO, C7_TPCOLAB, C7_IDTSS, C7_ALIQISS, C7_VALISS, C7_ALIQINS, C7_VALINS, C7_ALQCSL, C7_BASECSL, C7_CODNE, C7_ITEMNE, C7_FILCEN, C7_RETENCA, C7_QUJERET, C7_DEDUCAO, C7_QUJEDED, C7_FATDIRE, C7_QUJEFAT, C7_ACCPROC, C7_RATEIO, C7_FRETCON, C7_TRANSLJ, C7_TRANSP, C7_CODRDA, C7_BASEISS, C7_BASEINS, C7_VALCSL, C7_LOTPLS, C7_PLOPELT, C7_FISCORI, C7_DIREITO, C7_OBRIGA, C7_IDTRIB, D_E_L_E_T_, R_E_C_N_O_, R_E_C_D_E_L_, C7_ZZNUMQP, C7_XTIPOCP, C7_XTRANSP, C7_ZZVALID, C7_ZZTRANS, C7_XOBSITE, C7_USERLGI, C7_USERLGA, C7_XLOGALT, C7_BASPIS, C7_BASCOF, C7_ALQCF2, C7_VALPIS, C7_ALQPS2, C7_ALQPIS, C7_ALQCOF, C7_VALCOF, S_T_A_M_P_
FROM 
	PROTHEUS12_R27.dbo.SC7010
WHERE 
	C7_ZZNUMQP LIKE '%6963'
	AND D_E_L_E_T_ <> '*'
ORDER BY R_E_C_N_O_ DESC;


-- TOTAL DE PCs (ABERTAS E FECHADAS)
SELECT 
	COUNT(*) AS "TOTAL PC"
FROM 
	PROTHEUS12_R27.dbo.SC7010
WHERE 
	C7_ZZNUMQP LIKE '%6963'
	AND D_E_L_E_T_ <> '*';


-- TOTAL DE PCs (ABERTAS)
SELECT 
	COUNT(*) AS "PC ABERTO"
FROM 
	PROTHEUS12_R27.dbo.SC7010
WHERE 
	C7_ZZNUMQP LIKE '%6963'
	AND C7_ENCER <> 'E'
	AND D_E_L_E_T_ <> '*';


-- TOTAL DE PCs (FECHADAS) -> MATERIAL ENTREGUE
SELECT 
	COUNT(*) AS "PC FECHADO"
FROM 
	PROTHEUS12_R27.dbo.SC7010
WHERE 
	C7_ZZNUMQP LIKE '%6963'
	AND C7_ENCER = 'E'
	AND D_E_L_E_T_ <> '*';
